import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, BookOpen, Search, ShieldCheck, Truck, Upload } from "lucide-react";
import { useLanguage } from "@/lib/i18n";

const topics = [
  {
    id: "access",
    icon: ShieldCheck,
    en: { label: "Access & safety", title: "Start with responsible access", intro: "Gwave requires an explicit 21+ acknowledgement before entry. Restricted seed and farm channels also require a signed-in account and an account-level acknowledgement." , items: [["Why is the 21+ gate required?", "The gate records an active acknowledgement before the public experience begins. It is not a statement that every product is lawful in every location. You are responsible for following the laws that apply to your location."], ["Why can I see merchandise but not restricted products?", "Brand merchandise is the open catalogue. Seed and farm products are a separate restricted channel that requires authentication, a recorded acknowledgement, and any additional review required by the applicable rules."], ["How do I change my acknowledgement?", "Clear the local access record only when necessary, then reopen the gate. If you are signed in, Gwave may also record the account-level acknowledgement for the restricted workflow."]] },
    my: { label: "ဝင်ရောက်ခွင့်နှင့် လုံခြုံရေး", title: "တာဝန်ယူမှုရှိသော ဝင်ရောက်မှုဖြင့် စတင်ပါ", intro: "Gwave သို့ ဝင်ရောက်ရန် ၂၁+ အတည်ပြုချက်ကို မဖြစ်မနေ ပြုလုပ်ရပါမည်။ Seed နှင့် farm channel များအတွက် အကောင့်ဝင်ခြင်းနှင့် account-level acknowledgement ထပ်မံလိုအပ်ပါသည်။", items: [["၂၁+ gate ကို ဘာကြောင့် လိုအပ်သလဲ?", "ဤ gate သည် public experience မစတင်မီ အသုံးပြုသူ၏ အတည်ပြုချက်ကို မှတ်တမ်းတင်ရန် ဖြစ်ပါသည်။ နေရာတိုင်းတွင် ပစ္စည်းတိုင်း တရားဝင်သည်ဟု ကြေညာခြင်း မဟုတ်ပါ။ မိမိတည်နေရာနှင့် သက်ဆိုင်သော ဥပဒေများကို လိုက်နာရန် သုံးစွဲသူတွင် တာဝန်ရှိပါသည်။"], ["Merchandise ကို မြင်ရပေမယ့် restricted product ကို ဘာကြောင့် မမြင်ရသလဲ?", "Brand merchandise သည် open catalogue ဖြစ်ပြီး seed နှင့် farm product များသည် သီးခြား restricted channel ဖြစ်ပါသည်။ အကောင့်ဝင်ခြင်း၊ acknowledgement နှင့် သက်ဆိုင်ရာ ထပ်ဆင့်စစ်ဆေးမှုများ လိုအပ်ပါသည်။"], ["Acknowledgement ကို ဘယ်လို ပြန်ပြင်မလဲ?", "လိုအပ်မှသာ local access record ကို ရှင်းလင်းပြီး gate ကို ပြန်ဖွင့်ပါ။ အကောင့်ဝင်ထားပါက restricted workflow အတွက် account-level acknowledgement ကိုလည်း မှတ်တမ်းတင်နိုင်ပါသည်။"]] },
  },
  {
    id: "shop",
    icon: BookOpen,
    en: { label: "Store & products", title: "Choose the right channel", intro: "The Store separates public Gwave merchandise from restricted farm products. Product pages show available variants, stock, product details, and the next step to checkout.", items: [["What can I buy in the Brand Shop?", "The Brand Shop is for published Gwave merchandise such as apparel and utility objects. Availability, size, colour, variant, and stock are shown on the product record when staff have published them."], ["How do I choose a variant?", "Open a product detail page, select the available size or colour variant, and continue to checkout. Stock is checked again when the order is created."], ["Why is a product unavailable?", "A product may be unpublished, out of stock, missing an active variant, or restricted by the channel rules. Contact Gwave with the product name if you need clarification."]] },
    my: { label: "Store နှင့် ပစ္စည်းများ", title: "သင့်တော်သော channel ကို ရွေးချယ်ပါ", intro: "Store ထဲတွင် public Gwave merchandise နှင့် restricted farm product များကို ခွဲခြားထားပါသည်။ Product page တွင် variant၊ stock၊ product detail နှင့် checkout သို့ သွားမည့်အဆင့်ကို ပြသထားပါသည်။", items: [["Brand Shop တွင် ဘာတွေဝယ်နိုင်သလဲ?", "Brand Shop သည် Gwave အဝတ်အထည်နှင့် utility object များကဲ့သို့ ထုတ်ဝေထားသော merchandise များအတွက် ဖြစ်ပါသည်။ Size၊ အရောင်၊ variant နှင့် stock များကို staff က ထည့်သွင်းထားပါက product record တွင် ပြသပါမည်။"], ["Variant ကို ဘယ်လို ရွေးမလဲ?", "Product detail page ကို ဖွင့်ပြီး ရရှိနိုင်သော size သို့မဟုတ် အရောင် variant ကို ရွေးပါ။ ထို့နောက် checkout သို့ ဆက်သွားပါ။ Order ဖန်တီးချိန်တွင် stock ကို ထပ်မံစစ်ဆေးပါမည်။"], ["ပစ္စည်းကို ဘာကြောင့် မရနိုင်တာလဲ?", "ပစ္စည်းကို မထုတ်ဝေရသေးခြင်း၊ stock ကုန်ခြင်း၊ active variant မရှိခြင်း သို့မဟုတ် channel စည်းမျဉ်းကြောင့် ဖြစ်နိုင်ပါသည်။ အသေးစိတ်သိလိုပါက product name နှင့် Gwave ကို ဆက်သွယ်ပါ။"]] },
  },
  {
    id: "knowledge",
    icon: BookOpen,
    en: { label: "Knowledge & COA", title: "Read the source before the claim", intro: "The strain library separates source-approved information from independently verified laboratory evidence. Filters and profile fields are shown only when the required source data is present.", items: [["What does source-approved mean?", "It means the record was imported or reviewed against a named source. It does not mean that an independent laboratory Certificate of Analysis is attached."], ["What is a Verified COA?", "A Verified COA is a staff-reviewed laboratory document whose approved public summary may include lab name, report or batch reference, test date, cannabinoid results, and terpene summary. Private document keys are not exposed publicly."], ["Can I treat a strain page as medical advice?", "No. Knowledge pages are educational records and source summaries, not a diagnosis, prescription, or guarantee of a personal effect. Confirm local rules and consult an appropriately qualified professional for personal decisions."]] },
    my: { label: "Knowledge နှင့် COA", title: "Claim မယုံမီ source ကို ဖတ်ပါ", intro: "Strain library သည် source-approved အချက်အလက်နှင့် independent laboratory evidence ကို ခွဲခြားပြသပါသည်။ လိုအပ်သော source data ရှိမှသာ filter နှင့် profile field များကို ပြသပါသည်။", items: [["Source-approved ဆိုတာ ဘာလဲ?", "အမည်ဖော်ပြထားသော source တစ်ခုနှင့် တိုက်ဆိုင်စစ်ဆေးပြီး import သို့မဟုတ် review ပြုလုပ်ထားသော record ကို ဆိုလိုပါသည်။ Independent laboratory COA ပါရှိသည်ဟု မဆိုလိုပါ။"], ["Verified COA ဆိုတာ ဘာလဲ?", "Verified COA သည် staff က စစ်ဆေးအတည်ပြုထားသော laboratory document ဖြစ်ပါသည်။ Public summary တွင် lab name၊ report/batch reference၊ test date၊ cannabinoid result နှင့် terpene summary များ ပါနိုင်ပါသည်။ Private document key ကို public မဖော်ပြပါ။"], ["Strain page ကို ဆေးဘက်ဆိုင်ရာအကြံပြုချက်အဖြစ် သတ်မှတ်လို့ရသလား?", "မရပါ။ Knowledge page များသည် ပညာပေး record နှင့် source summary များသာဖြစ်ပြီး diagnosis၊ prescription သို့မဟုတ် ကိုယ်ပိုင်အကျိုးသက်ရောက်မှု အာမခံချက် မဟုတ်ပါ။ မိမိဆုံးဖြတ်ချက်အတွက် သက်ဆိုင်ရာဥပဒေနှင့် ကျွမ်းကျင်သူအကြံပြုချက်ကို စစ်ဆေးပါ။"]] },
  },
  {
    id: "orders",
    icon: Truck,
    en: { label: "Orders & delivery", title: "Keep your order traceable", intro: "Gwave uses an order reference and status history so customers and staff can identify the next action without exposing private internal documents.", items: [["What details are required at checkout?", "A signed-in customer provides an email address, phone number, delivery address, product, and selected variant. Use accurate details so staff can contact you about fulfilment."], ["How does payment-slip submission work?", "After an order is created, submit the permitted payment-slip image through the protected order workflow. Staff review the slip against the order reference and payment details. Do not send private slips through public social comments."], ["How do I ask about shipping or refund?", "Keep your order reference ready and contact Gwave through the listed support channel. Staff can check the status history, payment state, shipping note, and applicable policy before responding."]] },
    my: { label: "အော်ဒါနှင့် ပို့ဆောင်မှု", title: "သင့်အော်ဒါကို ခြေရာခံနိုင်အောင် ထိန်းသိမ်းပါ", intro: "Gwave သည် order reference နှင့် status history ကို အသုံးပြု၍ နောက်တစ်ဆင့်ကို ရှင်းလင်းစွာ သိနိုင်အောင် စီမံပါသည်။ Private internal document များကို customer ထံ မဖော်ပြပါ။", items: [["Checkout တွင် ဘာအချက်အလက် လိုအပ်သလဲ?", "အကောင့်ဝင်ထားသော customer သည် email၊ phone number၊ delivery address၊ product နှင့် ရွေးချယ်ထားသော variant ကို ထည့်ရပါမည်။ Fulfilment အတွက် staff ဆက်သွယ်နိုင်အောင် မှန်ကန်သောအချက်အလက် ထည့်ပါ။"], ["Payment-slip တင်ခြင်းကို ဘယ်လိုလုပ်မလဲ?", "Order ဖန်တီးပြီးနောက် protected order workflow မှတစ်ဆင့် ခွင့်ပြုထားသော payment-slip image ကို တင်ပါ။ Staff သည် order reference နှင့် payment detail ကို တိုက်ဆိုင်စစ်ဆေးပါမည်။ Public social comment ထဲတွင် private slip မပို့ပါနှင့်။"], ["Shipping သို့မဟုတ် refund အကြောင်း ဘယ်လိုမေးမလဲ?", "Order reference ကို အသင့်ပြင်ထားပြီး ဖော်ပြထားသော support channel မှတစ်ဆင့် Gwave ကို ဆက်သွယ်ပါ။ Staff သည် status history၊ payment state၊ shipping note နှင့် သက်ဆိုင်ရာ policy ကို စစ်ဆေးပြီး ပြန်လည်ဖြေကြားနိုင်ပါသည်။"]] },
  },
  {
    id: "policies",
    icon: ShieldCheck,
    en: { label: "Policies & privacy", title: "Know the rules before you submit", intro: "Gwave policies explain how contact details, order records, payment evidence, shipping, and refunds are handled. Read the linked policy pages before placing an order.", items: [["How is my personal information used?", "Gwave uses the contact and delivery details needed to create, support, and fulfil an order. Private payment slips and COA documents are handled through protected staff workflows and should not be shared publicly."], ["What should I check before shipping?", "Confirm that your destination can lawfully receive the selected category, that the address and phone number are accurate, and that any applicable delivery or destination restrictions have been reviewed."], ["When can I request a refund?", "Refund decisions depend on the applicable refund policy, payment state, stock or fulfilment condition, and any documented exception. Keep the order reference and contact Gwave through the support channel."]] },
    my: { label: "မူဝါဒနှင့် ကိုယ်ရေးအချက်အလက်", title: "မတင်သွင်းမီ စည်းမျဉ်းကို သိပါ", intro: "Gwave policy များတွင် contact detail၊ order record၊ payment evidence၊ shipping နှင့် refund များကို မည်သို့ စီမံသည်ကို ရှင်းလင်းထားပါသည်။ Order မပြုမီ သက်ဆိုင်ရာ policy page များကို ဖတ်ပါ။", items: [["ကိုယ်ရေးအချက်အလက်ကို ဘယ်လိုအသုံးပြုမလဲ?", "Gwave သည် order ဖန်တီးခြင်း၊ support နှင့် fulfilment အတွက် လိုအပ်သော contact နှင့် delivery detail များကို အသုံးပြုပါသည်။ Private payment slip နှင့် COA document များကို protected staff workflow ဖြင့် စီမံပြီး public မျှဝေမထားသင့်ပါ။"], ["Shipping မပြုမီ ဘာတွေစစ်ရမလဲ?", "ရွေးချယ်ထားသော category ကို မိမိ destination သို့ တရားဝင်ပို့နိုင်ခြင်း၊ address နှင့် phone number မှန်ကန်ခြင်း၊ delivery/destination restriction များကို စစ်ဆေးပြီးဖြစ်ခြင်းတို့ကို အတည်ပြုပါ။"], ["Refund ကို ဘယ်အချိန်တောင်းနိုင်မလဲ?", "Refund ဆုံးဖြတ်ချက်သည် သက်ဆိုင်ရာ refund policy၊ payment state၊ stock/fulfilment condition နှင့် မှတ်တမ်းတင်ထားသော exception များပေါ် မူတည်ပါသည်။ Order reference ကို ပြင်ဆင်ပြီး support channel မှတစ်ဆင့် Gwave ကို ဆက်သွယ်ပါ။"]] },
  },
  {
    id: "staff",
    icon: Upload,
    en: { label: "Staff & support", title: "Use the operations desk carefully", intro: "Staff surfaces are reserved for authorized users. Order status, payment slips, COA documents, and editorial records must be handled through the approved dashboard workflow.", items: [["Who can view payment slips?", "Only authorized staff or admin roles should retrieve private payment-slip objects. Access must use the protected signed retrieval procedure and must not be copied into public links."], ["Who can approve a COA?", "A staff reviewer can prepare or review a COA record according to the configured workflow. Public visibility should only be enabled after the required approval and audit evidence exists."], ["What should I do when a record looks wrong?", "Do not silently edit a published compliance record. Add a review note, preserve the audit trail, and escalate the issue to the responsible owner or compliance reviewer."]] },
    my: { label: "Staff နှင့် အကူအညီ", title: "Operations desk ကို သတိရှိစွာ အသုံးပြုပါ", intro: "Staff surface များသည် ခွင့်ပြုထားသော user များအတွက်သာ ဖြစ်ပါသည်။ Order status၊ payment slip၊ COA document နှင့် editorial record များကို dashboard workflow အတိုင်း စီမံရပါမည်။", items: [["Payment slip ကို ဘယ်သူတွေ ကြည့်နိုင်သလဲ?", "ခွင့်ပြုထားသော staff သို့မဟုတ် admin role များသာ private payment-slip object ကို ရယူသင့်ပါသည်။ Protected signed retrieval procedure ကို အသုံးပြုပြီး public link အဖြစ် မကူးယူရပါ။"], ["COA ကို ဘယ်သူ approve လုပ်နိုင်သလဲ?", "Staff reviewer သည် သတ်မှတ်ထားသော workflow အတိုင်း COA record ကို ပြင်ဆင် သို့မဟုတ် review လုပ်နိုင်ပါသည်။ လိုအပ်သော approval နှင့် audit evidence မရှိမချင်း public visibility မဖွင့်သင့်ပါ။"], ["Record မှားနေသည်ဟု တွေ့ပါက ဘာလုပ်မလဲ?", "Published compliance record ကို မည်သည့်မှတ်တမ်းမျှ မချန်ဘဲ တိတ်တဆိတ် မပြင်ပါနှင့်။ Review note ထည့်ပြီး audit trail ကို ထိန်းသိမ်းကာ တာဝန်ရှိသော owner သို့မဟုတ် compliance reviewer ထံ တင်ပြပါ။"]] },
  },
] as const;

export function Help() {
  const { language, t } = useLanguage();
  const [query, setQuery] = useState("");
  const normalized = query.trim().toLowerCase();
  const visibleTopics = useMemo(() => topics.filter(topic => {
    const content = topic[language];
    return !normalized || `${content.label} ${content.title} ${content.intro} ${content.items.flat().join(" ")}`.toLowerCase().includes(normalized);
  }), [language, normalized]);

  return <div className="mx-auto max-w-[1200px] px-4 py-16 md:px-8">
    <div className="grid gap-8 border-b border-white/20 pb-12 lg:grid-cols-[1fr_.8fr] lg:items-end">
      <div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Help / User guide</p><h1 className="mt-4 font-display text-6xl font-black uppercase leading-[.76] tracking-[-.09em] sm:text-8xl lg:text-9xl">{language === "my" ? <>သိကောင်းစရာ<br/><span className="text-[#8bd32c]">လမ်းညွှန်။</span></> : <>Know the<br/><span className="text-[#8bd32c]">system.</span></>}</h1></div>
      <p className="max-w-lg text-sm leading-7 text-white/60">{t("helpIntro")}</p>
    </div>
    <div className="mt-8 flex items-center gap-3 border border-white/25 bg-white/[.03] px-4"><Search className="size-4 shrink-0 text-[#8bd32c]"/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t("searchHelp")} className="h-14 w-full bg-transparent font-mono text-xs uppercase tracking-[.12em] outline-none placeholder:text-white/35" aria-label={t("searchHelp")} /></div>
    <div className="mt-10 grid gap-px bg-white/20 lg:grid-cols-2">{visibleTopics.map(topic => { const content = topic[language]; const Icon = topic.icon; return <section key={topic.id} className="bg-black p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8bd32c]">{content.label}</p><h2 className="mt-3 font-display text-4xl font-bold uppercase leading-none tracking-tight">{content.title}</h2></div><Icon className="size-7 shrink-0 text-[#8bd32c]" aria-hidden="true" /></div><p className="mt-5 text-sm leading-7 text-white/65">{content.intro}</p><div className="mt-6 grid gap-2">{content.items.map(([question, answer]) => <details key={question} className="border border-white/15 bg-white/[.02] p-4"><summary className="cursor-pointer font-display text-xl font-bold uppercase leading-tight marker:text-[#8bd32c]">{question}</summary><p className="mt-4 text-sm leading-7 text-white/65">{answer}</p></details>)}</div></section>; })}</div>
    {!visibleTopics.length && <div className="mt-8 border border-dashed border-white/25 p-6"><p className="font-display text-3xl font-bold uppercase">{t("noHelpResults")}</p></div>}
    <div className="mt-12 flex flex-wrap gap-3 border-t border-white/20 pt-6"><Link href="/contact" className="inline-flex items-center gap-2 bg-white px-4 py-3 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-black hover:bg-[#8bd32c]">{t("contact")} <ArrowRight className="size-4" /></Link><Link href="/store" className="inline-flex items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{language === "my" ? "Store သို့ သွားရန်" : "Go to store"} <ArrowRight className="size-4" /></Link><Link href="/knowledge" className="inline-flex items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{language === "my" ? "Knowledge သို့ သွားရန်" : "Open knowledge"} <ArrowRight className="size-4" /></Link><Link href="/checkout" className="inline-flex items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{language === "my" ? "Checkout" : "Checkout"} <ArrowRight className="size-4" /></Link><Link href="/orders" className="inline-flex items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{language === "my" ? "Orders" : "My orders"} <ArrowRight className="size-4" /></Link><Link href="/admin" className="inline-flex items-center gap-2 border border-white/30 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{language === "my" ? "Staff" : "Staff desk"} <ArrowRight className="size-4" /></Link></div>
  </div>;
}
