import { ArrowRight, Check, LockKeyhole, ShieldCheck, Truck } from "lucide-react";
import { Link } from "wouter";
import { useLanguage } from "@/lib/i18n";

const phases = [
  {
    number: "01",
    en: { label: "Launch readiness", title: "Trust before scale", copy: "Real product content, clear policies, responsible access, accurate stock, and a release gate that can be reviewed before public launch." },
    my: { label: "Launch readiness", title: "ချဲ့ထွင်မှုမတိုင်မီ ယုံကြည်မှု", copy: "အမှန်တကယ် product content၊ ရှင်းလင်းသော policy၊ တာဝန်ယူမှုရှိသော access၊ မှန်ကန်သော stock နှင့် public launch မတိုင်မီ စစ်ဆေးနိုင်သော release gate။" },
  },
  {
    number: "02",
    en: { label: "Trust & operations", title: "Evidence in process", copy: "Source-aware knowledge, real COA intake, auditable order states, private payment evidence, and staff workflows that preserve responsibility." },
    my: { label: "Trust & operations", title: "Process ထဲက သက်သေ", copy: "Source ကိုသိသာစွာဖော်ပြသော knowledge၊ အမှန်တကယ် COA၊ audit လုပ်နိုင်သော order state၊ private payment evidence နှင့် တာဝန်ရှိမှုကို ထိန်းသိမ်းသော staff workflow များ။" },
  },
  {
    number: "03",
    en: { label: "Commerce growth", title: "Brand with discipline", copy: "Brand Signal collections, useful news, social sharing, and repeat customer experience built on truthful content rather than inflated claims." },
    my: { label: "Commerce growth", title: "စည်းကမ်းရှိသော Brand", copy: "အမှန်တကယ်အကြောင်းအရာပေါ်တွင် တည်ဆောက်ထားသော Brand Signal collection၊ အသုံးဝင်သော news၊ social sharing နှင့် customer experience။" },
  },
  {
    number: "04",
    en: { label: "Mobile & scale", title: "Ready for the next surface", copy: "Android packaging, production monitoring, backups, performance budgets, and a carefully staged path to broader operations." },
    my: { label: "Mobile & scale", title: "နောက်ထပ် platform အတွက် အသင့်", copy: "Android packaging၊ production monitoring၊ backup၊ performance budget နှင့် လုပ်ငန်းချဲ့ထွင်မှုကို အဆင့်လိုက် ဆောင်ရွက်ခြင်း။" },
  },
];

const gates = [
  { en: "Product content, variants, stock, price, images, and policy links are complete.", my: "Product content၊ variant၊ stock၊ ဈေးနှုန်း၊ ပုံနှင့် policy link များ ပြည့်စုံခြင်း။" },
  { en: "Age access and restricted server procedures have no known bypass path.", my: "Age access နှင့် restricted server procedure များတွင် bypass လမ်းကြောင်း မရှိခြင်း။" },
  { en: "Payment method, slip review, support owner, and refund rules are clear.", my: "Payment method၊ slip review၊ support owner နှင့် refund rule များ ရှင်းလင်းခြင်း။" },
  { en: "Source-approved records and laboratory COA evidence remain visibly separate.", my: "Source-approved record နှင့် laboratory COA evidence ကို မြင်သာစွာ ခွဲခြားထားခြင်း။" },
  { en: "TypeScript, tests, build, responsive smoke checks, backup, and rollback are ready.", my: "TypeScript၊ tests၊ build၊ responsive smoke check၊ backup နှင့် rollback အသင့်ဖြစ်ခြင်း။" },
];

const kpis = [
  ["01", "Access", "Age-gate completion, restricted denials, bypass incidents"],
  ["02", "Knowledge", "Source coverage, editorial review, real COA approvals"],
  ["03", "Orders", "Payment review time, status aging, fulfilment exceptions"],
  ["04", "Security", "Unauthorized retrievals, audit coverage, private-file incidents"],
  ["05", "Experience", "Mobile performance, errors, checkout completion, repeat use"],
];

export function Roadmap() {
  const { language } = useLanguage();
  const my = language === "my";
  return <div className="mx-auto max-w-[1400px] px-4 py-16 md:px-8">
    <section className="grid gap-10 border-b border-white/20 pb-16 lg:grid-cols-[1.15fr_.85fr] lg:items-end">
      <div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Gwave / Roadmap & Trust</p><h1 className="mt-4 font-display text-6xl font-black uppercase leading-[.75] tracking-[-.09em] sm:text-8xl lg:text-9xl">{my ? <>ယုံကြည်မှုကို<br/><span className="text-[#8bd32c]">တည်ဆောက်မည်။</span></> : <>Build the<br/><span className="text-[#8bd32c]">standard.</span></>}</h1></div>
      <div className="border-l-2 border-[#8bd32c] pl-5 text-sm leading-7 text-white/70"><p>{my ? "Gwave သည် online shop တစ်ခုတည်းမဟုတ်ဘဲ source-aware knowledge၊ compliance-led process နှင့် တာဝန်ရှိသော order operation တို့ကို ပေါင်းစည်းထားသော platform ဖြစ်လာရန် ရည်ရွယ်ပါသည်။" : "Gwave is being built as more than a shop: a source-aware knowledge platform, a compliance-led process, and a responsible order operation in one place."}</p><p className="mt-5 font-mono text-[10px] uppercase tracking-[.18em] text-[#8bd32c]">Raw in visual language. Verified in process. Clear in responsibility.</p></div>
    </section>

    <section className="border-b border-white/20 py-16"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">The path</p><h2 className="mt-3 font-display text-5xl font-black uppercase tracking-[-.07em] sm:text-7xl">{my ? "အဆင့်လေးဆင့်" : "Four phases"}</h2></div><p className="max-w-md text-sm leading-7 text-white/55">{my ? "Feature များကို အလျင်အမြန်ထည့်ခြင်းထက် legality၊ safety၊ data quality နှင့် brand quality ကို အဆင့်လိုက် တည်ဆောက်မည်။" : "The next stage is not about adding features as quickly as possible. It is about building legality, safety, data quality, and brand quality in sequence."}</p></div><div className="mt-10 grid gap-px bg-white/20 md:grid-cols-2">{phases.map(phase => { const content = phase[language]; return <article key={phase.number} className="bg-black p-6 sm:p-8"><span className="font-mono text-xs text-[#8bd32c]">{phase.number}</span><p className="mt-12 font-mono text-[10px] uppercase tracking-[.2em] text-white/45">{content.label}</p><h3 className="mt-3 font-display text-4xl font-bold uppercase leading-[.85] tracking-tight">{content.title}</h3><p className="mt-5 max-w-lg text-sm leading-7 text-white/60">{content.copy}</p></article>; })}</div></section>

    <section className="grid gap-8 border-b border-white/20 py-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Trust foundation</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.8] tracking-[-.07em] sm:text-7xl">{my ? <>မဖြစ်မနေ<br/>စစ်ဆေးရန်။</> : <>Release<br/>gates.</>}</h2><p className="mt-6 max-w-sm text-sm leading-7 text-white/60">{my ? "Public launch မတိုင်မီ အောက်ပါအချက်များကို သက်သေပြနိုင်ရမည်။" : "Before a public launch, each gate should be demonstrably ready—not merely promised."}</p></div><div className="grid gap-3">{gates.map((gate, index) => <div key={index} className="flex gap-4 border border-white/15 bg-white/[.02] p-4"><Check className="mt-0.5 size-5 shrink-0 text-[#8bd32c]"/><p className="text-sm leading-6 text-white/70">{gate[language]}</p></div>)}</div></section>

    <section className="grid gap-8 border-b border-white/20 py-16 lg:grid-cols-[1fr_1.25fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Responsibility by design</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.8] tracking-[-.07em] sm:text-7xl">{my ? <>Source ကို<br/>မဖုံးကွယ်ပါ။</> : <>No claim<br/>without source.</>}</h2><p className="mt-6 max-w-md text-sm leading-7 text-white/60">{my ? "Source-approved strain record ကို independent laboratory COA အဖြစ် မဖော်ပြပါ။ Private document များကို public link ဖြင့် မမျှဝေပါ။" : "A source-approved strain record is not an independent laboratory COA. Private documents should never be turned into public links."}</p></div><div className="grid gap-px bg-white/20 sm:grid-cols-3"><div className="bg-black p-6"><ShieldCheck className="size-7 text-[#8bd32c]"/><p className="mt-8 font-display text-2xl font-bold uppercase">{my ? "Access" : "Access"}</p><p className="mt-3 text-sm leading-6 text-white/55">{my ? "၂၁+ နှင့် restricted boundary" : "21+ and restricted boundaries"}</p></div><div className="bg-black p-6"><LockKeyhole className="size-7 text-[#8bd32c]"/><p className="mt-8 font-display text-2xl font-bold uppercase">{my ? "Evidence" : "Evidence"}</p><p className="mt-3 text-sm leading-6 text-white/55">{my ? "COA နှင့် audit trail" : "COA and audit trails"}</p></div><div className="bg-black p-6"><Truck className="size-7 text-[#8bd32c]"/><p className="mt-8 font-display text-2xl font-bold uppercase">{my ? "Fulfilment" : "Fulfilment"}</p><p className="mt-3 text-sm leading-6 text-white/55">{my ? "Order နှင့် shipping မှတ်တမ်း" : "Order and shipping records"}</p></div></div></section>

    <section className="border-b border-white/20 py-16"><div className="flex items-end justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Measure the work</p><h2 className="mt-3 font-display text-5xl font-black uppercase tracking-[-.07em] sm:text-7xl">{my ? "အောင်မြင်မှုကို တိုင်းမည်။" : "Measure what matters."}</h2></div><p className="hidden max-w-sm text-sm leading-7 text-white/55 md:block">{my ? "Page view တစ်ခုတည်းမဟုတ်ဘဲ trust၊ order quality၊ source quality နှင့် operational response တို့ကို တိုင်းတာမည်။" : "Success is more than page views: measure trust, order quality, source quality, and operational response."}</p></div><div className="mt-10 grid gap-px bg-white/20 sm:grid-cols-2 lg:grid-cols-5">{kpis.map(([number, title, copy]) => <div key={number} className="bg-black p-5"><span className="font-mono text-xs text-[#8bd32c]">{number}</span><h3 className="mt-10 font-display text-2xl font-bold uppercase">{my ? ["ဝင်ရောက်မှု", "Knowledge", "အော်ဒါ", "လုံခြုံရေး", "အသုံးပြုမှု"][Number(number) - 1] : title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{my ? ["Age gate နှင့် restricted access", "Source၊ editorial review၊ COA", "Payment နှင့် fulfilment အချိန်", "Unauthorized access နှင့် audit", "Mobile performance နှင့် repeat use"][Number(number) - 1] : copy}</p></div>)}</div></section>

    <section className="border-b border-white/20 py-16"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#8bd32c]">Risk register</p><h2 className="mt-3 font-display text-5xl font-black uppercase leading-[.8] tracking-[-.07em] sm:text-7xl">{my ? <>အန္တရာယ်ကို<br/>ကြိုတင်စီမံ။</> : <>Name the<br/>risk.</>}</h2><p className="mt-6 max-w-sm text-sm leading-7 text-white/60">{my ? "တရားဝင်မှု၊ data quality၊ payment၊ privacy နှင့် fulfilment အန္တရာယ်များကို ဖုံးကွယ်မထားဘဲ owner နှင့် review လုပ်မည့်အချက်ကို ကြိုတင်သတ်မှတ်မည်။" : "Legal, data, payment, privacy, and fulfilment risks stay visible with an owner and a review action—not hidden behind the interface."}</p></div><div className="grid gap-3 sm:grid-cols-2">{(my ? [["Legal / access", "ဒေသအလိုက် rule ပြောင်းလဲမှုများကို launch မတိုင်မီ ပြန်စစ်မည်။"], ["Data / COA", "Source-approved နှင့် lab evidence ကို မရောထွေးစေဘဲ review status ထိန်းသိမ်းမည်။"], ["Payment / privacy", "Slip နှင့် private document များကို signed staff workflow ဖြင့်သာ ကိုင်တွယ်မည်။"], ["Fulfilment", "Stock၊ address၊ destination နှင့် support escalation ကို order reference ဖြင့် ခြေရာခံမည်။"]] : [["Legal / access", "Re-check local rules, age policy, and restricted-channel eligibility before launch."], ["Data / COA", "Keep source-approved records separate from laboratory evidence and review status."], ["Payment / privacy", "Handle slips and private documents only through signed staff workflows."], ["Fulfilment", "Track stock, address, destination, and support escalation by order reference."]]).map(([title, copy]) => <div key={title} className="border border-white/15 bg-white/[.02] p-5"><p className="font-display text-2xl font-bold uppercase">{title}</p><p className="mt-3 text-sm leading-6 text-white/55">{copy}</p></div>)}</div></div></section>

    <section className="pt-14"><div className="border border-[#8bd32c]/70 bg-[#8bd32c]/[.06] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8bd32c]">90-day direction</p><h2 className="mt-3 font-display text-4xl font-black uppercase sm:text-6xl">{my ? "အဆင့်လိုက် အကောင်အထည်ဖော်မည်။" : "Ship the standard."}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70">{my ? "ပထမ ၉၀ ရက်တွင် real product content၊ staff operations၊ COA intake၊ content calendar၊ production readiness နှင့် soft launch ကို ဦးစားပေးပါမည်။" : "Over the first 90 days, Gwave prioritizes real product content, staff operations, COA intake, a content calendar, production readiness, and a measured soft launch."}</p></div><div className="flex flex-wrap gap-3"><Link href="/help" className="inline-flex items-center gap-2 bg-white px-4 py-3 font-mono text-[10px] font-bold uppercase tracking-[.16em] text-black hover:bg-[#8bd32c]">{my ? "အသုံးပြုနည်း" : "User guide"} <ArrowRight className="size-4"/></Link><Link href="/contact" className="inline-flex items-center gap-2 border border-white/35 px-4 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-white/75 hover:border-[#8bd32c] hover:text-[#8bd32c]">{my ? "ဆက်သွယ်ရန်" : "Contact"} <ArrowRight className="size-4"/></Link></div></div></div></section>
  </div>;
}
